### ISSUE TITLE
  createMySQLXMLDataSet memory consumption

### ISSUE THREAD

**Issue by klevin** [sebastianbergmann/dbunit#157]
710MB & 5.85 min run time to load a 51MB file generated by `mysqldump --xml` seems excessive.

This is running on an Arch Linux 64-bit system, php v5.6.7 and the PHPUnit v4.6.2 phar.

**Comment by elazar** [comment]
I would suggest using a profiler like [Xdebug](http://xdebug.org/) (with one of [WinCacheGrind](http://ceefour.github.io/wincachegrind/) / [MacCallGrind](http://www.maccallgrind.com/) / [KCacheGrind](http://kcachegrind.sourceforge.net/html/Home.html) / [WebGrind](https://github.com/jokkedk/webgrind)) or [xhprof](http://pecl.php.net/package/xhprof) (with [xhgui](https://github.com/perftools/xhgui)) to isolate what's causing the inflated memory usage.

Offhand, I know that `createMySQLXMLDataSet()` simply returns an instance of [`MysqlXmlDataSet`](https://github.com/sebastianbergmann/dbunit/blob/master/PHPUnit/Extensions/Database/DataSet/MysqlXmlDataSet.php), which extends [`AbstractXmlDataSet`](https://github.com/sebastianbergmann/dbunit/blob/master/PHPUnit/Extensions/Database/DataSet/AbstractXmlDataSet.php), which uses [SimpleXML](http://php.net/simplexml) for parsing. That coupled with an XML file that large may be contributing to the excessive memory usage and runtime you're seeing.

If that is indeed the issue, refactoring `AbstractXmlDataSet` and its subclasses to use something other than SimpleXML is a non-trivial project; I'd suggest creating and using your own data set implementation using something like [XMLReader](http://php.net/xmlreader) instead of SimpleXML to confirm that addresses the issue.

**Comment by sebastianbergmann** [comment]
Using SimpleXML is almost always a bad idea. XMLReader would be a good XML API for this task, I think.
